### ISSUE TITLE
I am having trouble switching over from Blueprints+ to BlueprintX

### ISSUE THREAD

**Issue by Ellie-Is-Smart** [Thundernerd/Modkist#5]
I read in the description of blueprintX that if you still have blueprint+ installed it will not run. I can't find out where I would have Blueprints+ installed since it is not on Modkist (looks like it has been replaced with blueprintX). I am not able to use any of the level editor assets I can't find the blue folder mentioned in the blueprinX description.

**Comment by Thundernerd** [comment]
You can follow the following steps to get rid of BlueprintsPlus if you still have it installed.

![image](https://github.com/Thundernerd/Modkist/assets/5531467/56e41a8e-fefb-4a9e-ae58-f9e9ff0bf7fe)

1. Click the `Collection` button
2. Locate `BlueprintsPlus` in the list
3. Click the `Subscribe` button

Following these steps should help you get rid of BlueprintsPlus.

I would also suggest you join the modding discord for faster help: https://discord.com/invite/5PwjrMHmgZ
