### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by inikishev** [Thundernerd/Modkist#6]
I launch zeepkist through modkist but it just launches regular zeepkist without mods. I also had the same issue one year ago but I don't remember how I solved it and I can't find the issue where I solved it

**Comment by Thundernerd** [comment]
When running into issues like this it is recommended that you join the modding discord: https://discord.gg/8bcuGmcZ

**Comment by inikishev** [comment]
> When running into issues like this it is recommended that you join the modding discord: https://discord.gg/8bcuGmcZ

could you make another one it says invalid invite

**Comment by Thundernerd** [comment]
> > When running into issues like this it is recommended that you join the modding discord: https://discord.gg/8bcuGmcZ
> 
> could you make another one it says invalid invite

Here you go: https://discord.gg/8EqW9pUFTX
